DROP TABLE IF EXISTS Events;
CREATE TABLE
IF NOT EXISTS Customers
(Id TEXT PRIMARY KEY, Blob JSON);

CREATE TABLE
IF NOT EXISTS Participants
(EventId Text PRIMARY KEY, Name TEXT PRIMARY KEY, Blob JSON);