name = "secretsanta"
compatibility_date = "2023-01-01"

r2_buckets  = [
  { binding = "SecretSantaBucket", bucket_name = "secretsanta2", preview_bucket_name="secretsantapreview"}
]

kv_namespaces = [
    { binding = "SecretSanta", id = "4d1ebcc717eb49bfb731f7172059fe63",preview_id = "51144b53a8654b1ab4e57727ef389993" }
]

d1_databases = [
    {binding = "DB",database_name = "secretsanta",database_id = "b849c4ac-4d24-45af-8b1d-c0fbf468eda4"}
]

