name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker/secretSanta

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy with Wrangler
      uses: cloudflare/wrangler-action@v3.1.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      env:
        CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

