name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker/secretSanta

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use the Node.js version that matches your project

    - name: Install Wrangler
      run: npm install -g @cloudflare/wrangler

    - name: Install Dependencies
      run: npm install

    - name: Authenticate with Cloudflare
      run: wrangler config
      env:
        CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    - name: Publish the Worker
      run: wrangler publish
      env:
        CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
